version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3.7.14-alpine"
    ports:
      - "5673:5672"
  producer:
    build: ./producer
    command: ["npm", "run", "firstStart"]
    container_name: mobility_producer
    ports:
      - "3000:3000"
    volumes:
      - ./producer:/api
      - /producer/node_modules
    depends_on:
      - rabbitmq
networks:
  default: